<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>RemoteAgent</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>3.0.0</Version>
    <FileVersion>3.0.0.0</FileVersion>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <InformationalVersion>3.0-rustdesk-remote-core</InformationalVersion>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <EmbeddedResource Include="..\..\ThirdParty\RustDesk\RustDeskRuntime.zip"
                      LogicalName="RemoteAgent.RustDeskRuntime.zip" />
    <PackageReference Include="System.Management" Version="10.0.10" />
    <ProjectReference Include="..\..\Shared\RemoteControl.Shared\RemoteControl.Shared.csproj" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.0" />
  </ItemGroup>
</Project>

